# Generated by Django 4.2.7 on 2023-11-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketHub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdb',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/media'),
        ),
    ]
