# Generated by Django 4.2.7 on 2023-11-24 14:59

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ticketHub', '0006_alter_eventdb_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdb',
            name='location',
            field=django_google_maps.fields.GeoLocationField(max_length=100),
        ),
    ]
