# Generated by Django 4.2.7 on 2023-11-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketHub', '0007_alter_eventdb_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdb',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
