# Generated by Django 4.2.7 on 2023-11-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketHub', '0008_alter_eventdb_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdb',
            name='description',
        ),
        migrations.AddField(
            model_name='eventdb',
            name='event_title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
