# Generated by Django 4.2.7 on 2023-11-25 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketHub', '0009_remove_eventdb_description_eventdb_event_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventdb',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='eventdb',
            old_name='event_title',
            new_name='Event_title',
        ),
        migrations.RenameField(
            model_name='eventdb',
            old_name='location',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='eventdb',
            old_name='image',
            new_name='Poster',
        ),
    ]
