# Generated by Django 4.2.7 on 2023-11-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketHub', '0010_rename_date_eventdb_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdb',
            name='Time',
            field=models.TimeField(null=True),
        ),
    ]
