# Generated by Django 4.2.7 on 2023-11-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketHub', '0013_purchase_tickettype_delete_ticket_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('advanced', 'Advanced'), ('gate', 'Gate'), ('vip', 'VIP'), ('vvip', 'VVIP')], max_length=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='TicketType',
        ),
    ]
