# Generated by Django 4.2.7 on 2023-11-25 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketHub', '0014_ticket_delete_purchase_delete_tickettype'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdb',
            name='advanced_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventdb',
            name='currency_symbol',
            field=models.CharField(default='Ksh', max_length=5),
        ),
        migrations.AddField(
            model_name='eventdb',
            name='gate_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventdb',
            name='vip_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventdb',
            name='vvip_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketHub.eventdb'),
        ),
    ]
