# Generated by Django 4.2.7 on 2023-11-26 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketHub', '0017_product_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
