# Generated by Django 4.2.7 on 2023-11-26 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketHub', '0020_alter_payment_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='calculated_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketHub.ticket'),
        ),
    ]
