# Generated by Django 4.2.7 on 2023-11-26 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketHub', '0021_payment_calculated_amount_alter_payment_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
    ]
