# Generated by Django 4.2.7 on 2023-11-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketHub', '0022_remove_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='calculated_amount',
            field=models.IntegerField(null=True),
        ),
    ]
