# Generated by Django 4.2.7 on 2023-11-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketHub', '0023_alter_payment_calculated_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdb',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
