# Generated by Django 4.2.7 on 2023-11-27 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketHub', '0024_eventdb_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='ticket',
        ),
    ]
